inherit_from:
  - .rubocop_todo.yml

Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

SpaceInsideHashLiteralBraces:
  Enabled: false

Encoding:
  Enabled: false

#LineLength:
  #Max: 100
