#!/bin/bash

bundle exec hammer -v csv:organizations      --verbose --csv-file test/data/organizations.csv
bundle exec hammer -v csv:users              --verbose --csv-file test/data/users.csv
bundle exec hammer -v csv:architectures      --verbose --csv-file test/data/architectures.csv
bundle exec hammer -v csv:partitiontables    --verbose --csv-file test/data/partitiontables.csv
bundle exec hammer -v csv:domains            --verbose --csv-file test/data/domains.csv
bundle exec hammer -v csv:puppetenvironments --verbose --csv-file test/data/puppetenvironments.csv
bundle exec hammer -v csv:operatingsystems   --verbose --csv-file test/data/operatingsystems.csv
bundle exec hammer -v csv:hosts              --verbose --csv-file test/data/hosts.csv